version: '3'

volumes:
  db:

services:
  autogpt:
    build:
      context: .
    container_name: autogpt
    ports:
      - 3000:3000
    volumes:
      - db:/app/db
      - .env:/app/.env
    restart: unless-stopped
